CREATE DATABASE CTYMAILINH;
USE CTYMAILINH;
GO
CREATE TABLE LoaiXe (
    MaLoai NVARCHAR(10) PRIMARY KEY,
    SoCho INT NOT NULL
);

CREATE TABLE Xe (
    MaXe NVARCHAR(10) PRIMARY KEY,
    HangXe NVARCHAR(50) NOT NULL,
    BienSoXe NVARCHAR(20) UNIQUE NOT NULL,
    MaLoai NVARCHAR(10) NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai)
);

CREATE TABLE Tuyen (
    MaTuyen NVARCHAR(10) PRIMARY KEY,
    DiemDen NVARCHAR(100) NOT NULL,
    QuangDuong INT NOT NULL
);

CREATE TABLE Khach (
    MaKhach NVARCHAR(10) PRIMARY KEY,
    TenKhach NVARCHAR(100) NOT NULL,
    DienThoai NVARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE HopDongThue (
    SoHD NVARCHAR(10) PRIMARY KEY,
    MaKhach NVARCHAR(10) NOT NULL,
    MaTuyen NVARCHAR(10) NOT NULL,
    MaLoai NVARCHAR(10) NOT NULL,
    SoLuongXe INT NOT NULL,
    NgayDi DATE NOT NULL,
    NgayVe DATE NOT NULL,
    FOREIGN KEY (MaKhach) REFERENCES Khach(MaKhach),
    FOREIGN KEY (MaTuyen) REFERENCES Tuyen(MaTuyen),
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai)
);

CREATE TABLE GiaThue (
    MaLoai NVARCHAR(10),
    MaTuyen NVARCHAR(10),
    GiaThue INT NOT NULL,
    PRIMARY KEY (MaLoai, MaTuyen),
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai),
    FOREIGN KEY (MaTuyen) REFERENCES Tuyen(MaTuyen)
);
