CREATE DATABASE CTYMAILINH;
USE CTYMAILINH;
GO
CREATE TABLE LoaiXe (
    MaLoai VARCHAR(10) PRIMARY KEY,
    SoCho INT NOT NULL
);

CREATE TABLE Xe (
    MaXe VARCHAR(10) PRIMARY KEY,
    HangXe VARCHAR(50) NOT NULL,
    BienSoXe VARCHAR(20) UNIQUE NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai)
);

CREATE TABLE Tuyen (
    MaTuyen VARCHAR(10) PRIMARY KEY,
    DiemDen VARCHAR(100) NOT NULL,
    QuangDuong INT NOT NULL
);

CREATE TABLE Khach (
    MaKhach VARCHAR(10) PRIMARY KEY,
    TenKhach VARCHAR(100) NOT NULL,
    DienThoai VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE HopDongThue (
    SoHD VARCHAR(10) PRIMARY KEY,
    MaKhach VARCHAR(10) NOT NULL,
    MaTuyen VARCHAR(10) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    SoLuongXe INT NOT NULL,
    NgayDi DATE NOT NULL,
    NgayVe DATE NOT NULL,
    FOREIGN KEY (MaKhach) REFERENCES Khach(MaKhach),
    FOREIGN KEY (MaTuyen) REFERENCES Tuyen(MaTuyen),
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai)
);

CREATE TABLE GiaThue (
    MaLoai VARCHAR(10),
    MaTuyen VARCHAR(10),
    GiaThue INT NOT NULL,
    PRIMARY KEY (MaLoai, MaTuyen),
    FOREIGN KEY (MaLoai) REFERENCES LoaiXe(MaLoai),
    FOREIGN KEY (MaTuyen) REFERENCES Tuyen(MaTuyen)
);
